CREATE DATABASE bd-wta;
use bd-wta;

CREATE TABLE USER(
    USER_ID  INTEGER NOT NULL AUTO_INCREMENT,
    USER_NOME VARCHAR(70) NOT NULL,
    USER_LOGIN VARCHAR(15) NOT NULL,
    USER_PASSWORD VARCHAR(70) NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE CLIENTS(
    CLI_ID INTEGER NOT NULL AUTO_INCREMENT,
    CLI_NOME VARCHAR(40) NOT NULL,
    CLI_EMAIL VARCHAR(100) NOT NULL,
    CLI_PASSWORD VARCHAR(70) NOT NULL,
    CONSTRAINT CLI_PK PRIMARY KEY (CLI_ID)
);